package com.example.tvm.shared.module

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import dagger.Module
import dagger.Provides
import javax.inject.Provider

@Module
object ViewModelFactoryModule {

    /**
     * We are using the Map generated by this provider, and search for an viewModel object in the 'providers'
     * Map that has the key  'modelClass'.
     */
    @Provides
    @JvmStatic
    public fun provideViewModelFactory(
        providers: Map<Class<out ViewModel>,
                @JvmSuppressWildcards Provider<ViewModel>>
    ): ViewModelProvider.Factory = ViewModelProviderFactoryImpl(providers)

}